---
apiVersion: v1
kind: Namespace
metadata:
  name: loadtest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: checkout-injector-config
  namespace: loadtest
data:
  DEMO_USER_ID: "57a98d98e4b00679b4a830af"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: checkout-fail-injector
  namespace: loadtest
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: checkout-injector
            image: weaveworksdemos/checkout-injector:latest
            imagePullPolicy: IfNotPresent
            env:
            - name: DEMO_USER_ID
              valueFrom:
                configMapKeyRef:
                  name: checkout-injector-config
                  key: DEMO_USER_ID
          nodeSelector:
            kubernetes.io/os: linux
