server.port=${port:8080}
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}
spring.application.name=shipping
management.health.defaults.enabled=false
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${zipkin_endpoint:http://${zipkin_host:zipkin}:9411/api/v2/spans}
management.tracing.enabled=${zipkin_enabled:false}
management.endpoints.web.exposure.include=prometheus,health
