---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: queue-master
  labels:
    name: queue-master
  namespace: sock-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: queue-master
  template:
    metadata:
      labels:
        name: queue-master
    spec:
      containers:
      - name: queue-master
        image: weaveworksdemos/queue-master:0.3.1
        env:
         - name: JAVA_OPTS
           value: -Xms64m -Xmx128m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom -Dzipkin_enabled=true -Dzipkin_host=otel-collector-opentelemetry-collector.platform.svc.cluster.local
         - name: MANAGEMENT_TRACING_ENABLED
           value: "true"
         - name: MANAGEMENT_ZIPKIN_TRACING_ENDPOINT
           value: "http://otel-collector-opentelemetry-collector.platform.svc.cluster.local:9411/api/v2/spans"
        resources:
          limits:
            cpu: 300m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 300Mi
        ports:
        - containerPort: 80
      nodeSelector:
        beta.kubernetes.io/os: linux
