name: ci

on:
  push:
    branches:
    - "*"  # run for branches
    tags:
    - "*"  # run for tags

jobs:
  # Validate that kustomize overlays render without errors
  kustomize-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Validate kind overlay
      run: kubectl kustomize deploy/kubernetes/overlays/kind
    - name: Validate eks overlay
      run: kubectl kustomize deploy/kubernetes/overlays/eks

